### PR TITLE
Migrate from JavaScript to TypeScript

### PR DESCRIPTION
**Pull request by ghost**
Process:
1. Made a new temporary project
2. Executed npx create-react-app my-app --template typescript
3. Copied over existing components and changed the extension to .tsx everywhere
4. Added assets.d.ts to let typescript know how/where to import assets like images (jpg, png)
5. Removed 'name' attribute from div (divs dont have a name attribute) and replaced it with 'id'-attribute for react-scroll
6. Fixed smaller type errors such as using strings where numbers should have been used

So from now on you should create files with the .tsx and .ts extension instead of .jsx and .js.
Explanation: .tsx / .jsx means there are react components with the special inline HTML syntax.

It was actually easier to just create a new empty project with typescript support than change the existing one.

### CODE REVIEW

**Comment by Charlotte-Natasha** [comment]
I wanted help with tailwind responsiveness for this project, not changing
it to typescript.

**Comment by ghost** [comment]
That would have been the next step, yes. I thought you wanted to switch to coding in TypeScript only?

Two possibilities now:
* accept the PR
* close the PR

It doesn't make much sense to add the tailwind changes with this PR open since quite a few things have changed. I'll make a new PR as soon as this problem is resolved.

What do you want to do?

**Comment by Charlotte-Natasha** [comment]
How do I close the PR.? I could try the same project in typescript buy I
don't want to change this one.

**Comment by ghost** [comment]
There should be a button. I would have assumed as the owner of the original repository you'd see it. I closed the PR myself now.

**Comment by Charlotte-Natasha** [comment]
Meybe there was I just didn't know what to do. Haven't really collaborated
much. I only know how to pull push and merge repos 😂😂😂😂..

Gosh now I feel like I know nothing but oohh well.. Thanks 😁.

**Comment by ghost** [comment]
No problem, you'll close the next PR then 😁.

**Comment by Charlotte-Natasha** [comment]
Hey, so this is creepy but just checking in to see if you are okay. How are
you doing with the thesis? It's December cheer up and be in good spirits.
Like I said if you get this I do hope that you are safe and healthy.

Kind Regards

**Pull request closed without merging**
